// <auto-generated />
using System;
using ClientsWebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClientsWebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250630110540_Updated")]
    partial class Updated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClientFounder", b =>
                {
                    b.Property<string>("ClientInn")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FoundersInn")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ClientInn", "FoundersInn");

                    b.HasIndex("FoundersInn");

                    b.ToTable("ClientFounder", (string)null);
                });

            modelBuilder.Entity("ClientsWebApi.Models.Client", b =>
                {
                    b.Property<string>("Inn")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Inn");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("ClientsWebApi.Models.Founder", b =>
                {
                    b.Property<string>("Inn")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Inn");

                    b.ToTable("Founders");
                });

            modelBuilder.Entity("ClientFounder", b =>
                {
                    b.HasOne("ClientsWebApi.Models.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientInn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClientsWebApi.Models.Founder", null)
                        .WithMany()
                        .HasForeignKey("FoundersInn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
